.dockerfilelintrc:
  rules:
    latest_tag: "off"
    sudo_usage: "off"

.github/workflows/ci.yaml:
  env:
    - DOCKER_IMAGE: adorsys/ci-build
      TAG: 1-full
      DIR: 1/full
      ALIASES: 'full latest'
      SQUASH: 'true'
    - DOCKER_IMAGE: adorsys/ci-build
      TAG: 2-ubi-8-java-8
      DIR: 2/generated/ubi-8-java-8
    - DOCKER_IMAGE: adorsys/ci-build
      TAG: 2-ubi-8-java-11
      DIR: 2/generated/ubi-8-java-11
    - DOCKER_IMAGE: adorsys/ci-build
      TAG: 2-ubi-8-java-17
      DIR: 2/generated/ubi-8-java-17
    - DOCKER_IMAGE: adorsys/ci-build
      TAG: 2-ubi-8-node-10
      DIR: 2/generated/ubi-8-node-10
    - DOCKER_IMAGE: adorsys/ci-build
      TAG: 2-ubi-8-node-12
      DIR: 2/generated/ubi-8-node-12
    - DOCKER_IMAGE: adorsys/ci-build
      TAG: 2-ubi-8-node-14
      DIR: 2/generated/ubi-8-node-14
    - DOCKER_IMAGE: adorsys/ci-build
      TAG: 2-ubi-8-node-16
      DIR: 2/generated/ubi-8-node-16
    - DOCKER_IMAGE: adorsys/ci-build
      TAG: 2-ubi-8-node-18
      DIR: 2/generated/ubi-8-node-18
    - DOCKER_IMAGE: adorsys/ci-build
      TAG: 2-ubi-8-java-8-node-10
      DIR: 2/generated/ubi-8-java-8-node-10
    - DOCKER_IMAGE: adorsys/ci-build
      TAG: 2-ubi-8-java-11-node-10
      DIR: 2/generated/ubi-8-java-11-node-10
    - DOCKER_IMAGE: adorsys/ci-build
      TAG: 2-ubi-8-java-17-node-10
      DIR: 2/generated/ubi-8-java-17-node-10
    - DOCKER_IMAGE: adorsys/ci-build
      TAG: 2-ubi-8-java-8-node-12
      DIR: 2/generated/ubi-8-java-8-node-12
    - DOCKER_IMAGE: adorsys/ci-build
      TAG: 2-ubi-8-java-11-node-12
      DIR: 2/generated/ubi-8-java-11-node-12
    - DOCKER_IMAGE: adorsys/ci-build
      TAG: 2-ubi-8-java-17-node-12
      DIR: 2/generated/ubi-8-java-17-node-12
    - DOCKER_IMAGE: adorsys/ci-build
      TAG: 2-ubi-8-java-8-node-14
      DIR: 2/generated/ubi-8-java-8-node-14
    - DOCKER_IMAGE: adorsys/ci-build
      TAG: 2-ubi-8-java-11-node-14
      DIR: 2/generated/ubi-8-java-11-node-14
    - DOCKER_IMAGE: adorsys/ci-build
      TAG: 2-ubi-8-java-17-node-14
      DIR: 2/generated/ubi-8-java-17-node-14
    - DOCKER_IMAGE: adorsys/ci-build
      TAG: 2-ubi-8-java-8-node-16
      DIR: 2/generated/ubi-8-java-8-node-16
    - DOCKER_IMAGE: adorsys/ci-build
      TAG: 2-ubi-8-java-11-node-16
      DIR: 2/generated/ubi-8-java-11-node-16
    - DOCKER_IMAGE: adorsys/ci-build
      TAG: 2-ubi-8-java-17-node-16
      DIR: 2/generated/ubi-8-java-17-node-16
    - DOCKER_IMAGE: adorsys/ci-build
      TAG: 2-ubi-8-java-17-node-18
      DIR: 2/generated/ubi-8-java-17-node-18
