services:
  ubi-8-java-8:
    image: adorsys/ci-build:ubi-8-java-8
    build: generated/ubi-8-java-8
  ubi-8-java-11:
    image: adorsys/ci-build:ubi-8-java-11
    build: generated/ubi-8-java-11
  ubi-8-node-10:
    image: adorsys/ci-build:ubi-8-node-10
    build: generated/ubi-8-node-10
  ubi-8-node-12:
    image: adorsys/ci-build:ubi-8-node-12
    build: generated/ubi-8-node-12
  ubi-8-java-8-node-10:
    image: adorsys/ci-build:ubi-8-java-8-node-10
    build: generated/ubi-8-java-8-node-10
  ubi-8-java-11-node-10:
    image: adorsys/ci-build:ubi-8-java-11-node-10
    build: generated/ubi-8-java-11-node-10
  ubi-8-java-8-node-12:
    image: adorsys/ci-build:ubi-8-java-8-node-12
    build: generated/ubi-8-java-8-node-12
  ubi-8-java-11-node-12:
    image: adorsys/ci-build:ubi-8-java-11-node-12
    build: generated/ubi-8-java-11-node-12
